# fly.toml
app = "dissertation-lifecycle"
primary_region = "den"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  DEBUG = "0"
  UPLOAD_ROOT = "/data/uploads"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

#  [[http_service.checks]]
#    method = "GET"
#    path = "/healthz"
#    interval = "15s"
#    timeout = "2s"
#    grace_period = "30s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1024mb"