# fly.toml
app = "dissertation-lifecycle"
primary_region = "den"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  DEBUG = "0"
  UPLOAD_ROOT = "/data/uploads"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    method = "GET"
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    grace_period = "120s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1024mb"

[deploy]
  # Run DB migrations (and optionally seed idempotent templates) on each deploy
  # release_command = "python manage.py migrate && python manage.py seed_templates --verbosity 0 || true"
  # 
  release_command = "python manage.py migrate"
