app = "dissertation-lifecycle"
primary_region = "den"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  DEBUG = "0"
  # Set these via `fly secrets` in production
  # SECRET_KEY = "..."
  # DATABASE_URL = "postgres://..."
  UPLOAD_ROOT = "/data/uploads"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  processes = ["app"]
  internal_port = 8000
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  [services.concurrency]
    type = "requests"
    hard_limit = 80
    soft_limit = 60

