from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='tracker/login.html'), name='login'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='tracker/password_reset_form.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='tracker/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='tracker/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='tracker/password_reset_complete.html'), name='password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('resend-activation/', views.resend_activation, name='resend_activation'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('healthz', views.healthz, name='healthz'),
    path('theme/toggle/', views.toggle_theme, name='toggle_theme'),

    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('project/new/', views.project_new, name='project_new'),
    path('tasks/<int:pk>/status/', views.task_status, name='task_status'),
    path('tasks/<int:pk>/target/', views.task_target, name='task_target'),
    path('tasks/<int:pk>/', views.task_detail, name='task_detail'),
    path('tasks/<int:pk>/edit/', views.task_edit, name='task_edit'),
    path('tasks/<int:pk>/move/<str:direction>/', views.task_move, name='task_move'),
    path('tasks/new/', views.task_new, name='task_new'),
    path('tasks/<int:pk>/delete/', views.task_delete, name='task_delete'),
    path('tasks/<int:pk>/guidance/', views.task_guidance, name='task_guidance'),
    path('tasks/<int:pk>/upload/', views.upload_document, name='upload_document'),
    path('documents/<int:pk>/delete/', views.delete_document, name='delete_document'),
    path('documents/<int:pk>/edit/', views.edit_document, name='edit_document'),
    path('writing/', views.wordlogs, name='wordlogs'),
    path('writing/export.csv', views.wordlogs_csv, name='wordlogs_csv'),
    path('feedback/', views.feedback, name='feedback'),
    path('export.zip', views.my_export_zip, name='my_export_zip'),
    path('notes/', views.project_notes, name='project_notes'),
    path('notes/<int:pk>/edit/', views.project_note_edit, name='project_note_edit'),
    path('notes/<int:pk>/delete/', views.project_note_delete, name='project_note_delete'),
    path('advisor/', views.advisor_dashboard, name='advisor_dashboard'),
    path('advisor/projects/<int:pk>/', views.advisor_project, name='advisor_project'),
    path('advisor/projects/<int:pk>/export.json', views.advisor_project_export_json, name='advisor_project_export_json'),
    path('advisor/projects/<int:pk>/export.csv', views.advisor_project_export_csv, name='advisor_project_export_csv'),
    path('advisor/projects/<int:pk>/export.zip', views.advisor_project_export_zip, name='advisor_project_export_zip'),
    path('advisor/projects/<int:pk>/wordlogs.csv', views.advisor_project_wordlogs_csv, name='advisor_project_wordlogs_csv'),
    path('advisor/export.json', views.advisor_export_json, name='advisor_export_json'),
    path('advisor/export.csv', views.advisor_export_csv, name='advisor_export_csv'),
    path('advisor/export_import.csv', views.advisor_export_import_csv, name='advisor_export_import_csv'),
    path('advisor/import/', views.advisor_import, name='advisor_import'),
    path('advisor/import/template.csv', views.advisor_import_template, name='advisor_import_template'),
    # ICS calendar feeds
    path('calendar.ics', views.calendar_ics, name='calendar_ics'),
    path('advisor/calendar.ics', views.advisor_calendar_ics, name='advisor_calendar_ics'),
    path('calendar/token/<str:token>.ics', views.calendar_ics_token, name='calendar_ics_token'),
    path('advisor/calendar/token/<str:token>.ics', views.advisor_calendar_ics_token, name='advisor_calendar_ics_token'),
    path('calendar/settings/', views.calendar_settings, name='calendar_settings'),
    # Drag-and-drop reorder/move
    path('tasks/reorder/', views.task_reorder, name='task_reorder'),
]
