# Generated by Django 4.2.23 on 2025-08-31 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task_user_notes_projectnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='word_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_logs', to='tracker.task'),
        ),
    ]
