# Generated by Django 4.2.23 on 2025-08-31 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_task_word_target_wordlog_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSectionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('introduction', 'Introduction'), ('literature_review', 'Literature Review'), ('methodology', 'Methodology'), ('findings', 'Findings'), ('conclusion', 'Conclusion')], max_length=32)),
                ('percent', models.PositiveIntegerField(default=0)),
                ('word_target', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_sections', to='tracker.project')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('project', 'key')},
            },
        ),
    ]
