# Generated by Django 4.2.23 on 2025-09-01 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_coresectionprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.document'),
        ),
        migrations.DeleteModel(
            name='CoreSectionProgress',
        ),
    ]
