name: Tests (Unit + E2E)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'tracker/**'
      - 'requirements*.txt'
      - '.github/workflows/e2e.yml'
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run unit tests
        env:
          PYTHONWARNINGS: ignore::DeprecationWarning
        run: |
          pytest -q -m "not e2e"

  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    name: E2E on ${{ matrix.browser }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Install Playwright Browsers
        uses: microsoft/playwright-github-action@v1

      - name: Run E2E tests (headless)
        env:
          PYTHONWARNINGS: ignore::DeprecationWarning
        run: |
          pytest -m e2e -q --browser ${{ matrix.browser }}
