name: Scheduled Notifications

on:
  schedule:
    - cron: '0 9 * * *' # daily at 09:00 UTC
  workflow_dispatch:
    inputs:
      due_days:
        description: Days ahead to warn for due tasks
        required: false
        default: '3'
      inactivity_days:
        description: Days without logs to nudge
        required: false
        default: '5'
      digest_window_days:
        description: Window for advisor digest
        required: false
        default: '7'

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_APP_NAME: ${{ vars.FLY_APP_NAME }}
      DUE_DAYS: ${{ github.event.inputs.due_days || vars.NOTIFY_DUE_DAYS }}
      INACTIVE_DAYS: ${{ github.event.inputs.inactivity_days || vars.NOTIFY_INACTIVE_DAYS }}
      DIGEST_WINDOW_DAYS: ${{ github.event.inputs.digest_window_days || vars.NOTIFY_DIGEST_WINDOW_DAYS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Run notifications
        shell: bash
        run: |
          set -euo pipefail
          APP_NAME="${FLY_APP_NAME:-dissertation-lifecycle}"
          DUE="${DUE_DAYS:-3}"
          INACT="${INACTIVE_DAYS:-5}"
          DW="${DIGEST_WINDOW_DAYS:-7}"
          echo "Running notify on $APP_NAME (due=$DUE, inactive=$INACT, digest=$DW)"
          flyctl ssh console -a "$APP_NAME" -C \
            "python manage.py notify --due-days $DUE --inactivity-days $INACT --backup-reminder --advisor-digest --digest-window-days $DW"

